use crate::events::EventsHandler;
use common::cmd::OrderCommand;
use processors::{
    journaling::JournalingProcessor, matching_engine::MatchingEngineRouter, risk_engine::RiskEngine,
};
use std::sync::Arc;
use tokio::sync::mpsc;
use tracing::warn;

/// The central processing unit of the exchange, running a sequential pipeline.
/// This is the equivalent of `CoreEngine.java` orchestrating the processors.
pub struct CoreEngine {
    command_rx: mpsc::Receiver<OrderCommand>,
    risk_engine: RiskEngine,
    matching_engine_router: MatchingEngineRouter,
    journaling_processor: JournalingProcessor,
    events_handler: Arc<dyn EventsHandler>,
}

impl CoreEngine {
    pub fn new(
        command_rx: mpsc::Receiver<OrderCommand>,
        risk_engine: RiskEngine,
        matching_engine_router: MatchingEngineRouter,
        journaling_processor: JournalingProcessor,
        events_handler: Arc<dyn EventsHandler>,
    ) -> Self {
        Self {
            command_rx,
            risk_engine,
            matching_engine_router,
            journaling_processor,
            events_handler,
        }
    }

    /// The main processing loop, executing each processor's logic in sequence.
    pub async fn run(&mut self) {
        println!("\n[Sequential Core] Engine started. Waiting for commands...");
        while let Some(mut cmd) = self.command_rx.recv().await {
            println!(
                "\n[Sequential Core] ------ Processing Command ID: {} symbol_id {} ------",
                cmd.order_id, cmd.symbol
            );

            // 0: Journal the incoming command for durability. -- excali-0
            self.journaling_processor.journal_command(&cmd);

            // 1: Risk Engine validates the command(DONE) and holds funds(TODO). -- excali 5a, 5b
            if let Err(e) = self.risk_engine.pre_process_command(&mut cmd) {
                warn!(
                    "[Sequential Core] Risk check failed: {:?}. Rejecting command.",
                    e
                );
                continue;
            }

            // 2: Matching Engine processes the order and generates events. -- excali 6b, 7
            self.matching_engine_router.route_command(&mut cmd);

            // 3: Handle all events generated by the matching stage.
            let mut current_event = cmd.matcher_event.take();
            // check if fails: current_event how many events
            if current_event.is_none() {
                warn!(
                    "[Sequential Core] No events generated for command ID: {}",
                    cmd.order_id
                );
                continue;
            }
            println!(
                "[Sequential Core] Processing events for command ID: {}",
                cmd.order_id
            );
            while let Some(event_box) = current_event {
                let mut event = *event_box;
                current_event = event.next_event.take();
                println!("[Sequential Core] Processing event: {event:?}");

                // 3a. Journal the resulting event. -- excali 0
                self.journaling_processor.journal_event(&event);
                println!("[Sequential Core] Event journaled: {event:?}");

                // 3b. Risk Engine handles financial settlement. -- excali 8a
                self.risk_engine.handle_event(&event);
                println!("[Sequential Core] Risk Engine processed event: {event:?}");

                // 3c. External handler sends results to clients. -- excali 8b
                self.events_handler.handle_event(event.clone()).await;
                println!("[Sequential Core] Event sent to external handler: {event:?}");
            }
        }
        println!("[Sequential Core] Engine stopped.");
    }
}
