use crate::{L2MarketData, OrderCommandType, Side, TimeInForce, UserBalance};
use borsh::{BorshDeserialize, BorshSerialize};
use sbe_order::message_header_codec::{self, MessageHeaderDecoder};
use sbe_order::order_command_message_codec::{
    OrderCommandMessageDecoder, OrderCommandMessageEncoder, SBE_BLOCK_LENGTH, SBE_TEMPLATE_ID,
};
use sbe_order::status::Status as SbeStatus;
use sbe_order::{ReadBuf, SBE_SCHEMA_ID, SbeResult, WriteBuf};
use serde::de::Error;
use serde::de::value::Error as SerdeError;
use serde::{Deserialize, Serialize};
use std::fmt;
use std::ops::{Deref, DerefMut};

// Size of the serialized OrderCommand in bytes
// Header: 8 bytes
// command: 1 byte
// order_id: 8 bytes
// timestamp: 8 bytes
// user_id: 8 bytes
// market_id: 4 bytes
// price: 8 bytes
// size: 8 bytes
// side: 1 byte
// time_in_force: 1 byte
pub const ORDERCOMMANDSIZE: usize = 64;

/// This is the size of each frame sent or received via Aeron.
/// It is a nearest multiple of 32 bytes that can hold an OrderCommand.
pub const FRAMESIZE: i64 = 96;

/// OrderCommand: OrderCommand Plays the central role throughout the processing of the Order.
/// It is created in the Gateway, and processed in VexCore in different processors through the Disruptor
#[derive(Debug, Clone, PartialEq, Eq)]
#[repr(C)]
pub struct OrderCommand {
    // --- Universal Fields (Relevant for all command types) ---
    /// The type of command this struct represents. Consumers **must** check this
    /// field first to determine how to process the rest of the data.
    pub command: OrderCommandType,

    /// Client Order ID
    pub client_order_id: u64,

    /// The primary identifier for the order. Its meaning depends on `command`.
    /// - For `PlaceOrder`: This is the **new**, unique ID generated by the gateway.
    /// - For `CancelOrder`: This is the ID of the **existing** order to be canceled.
    pub order_id: u64,

    /// The unique identifier of the user initiating the command.
    /// For `PlaceOrder`, this is the owner of the new order.
    /// For `CancelOrder`, this is the caller whose ownership of the existing order is checked.
    /// Gateway response routing uses `route_gateway_id`, not this field.
    pub user_id: u64,

    /// The identifier for the market this command targets.
    pub market_id: u32,

    // --- `PlaceOrder`-Specific Fields ---
    // These fields are only valid if `command` is `PlaceOrder`. They are
    // undefined for `CancelOrder` and should be ignored by the processor.
    /// The price for the new order, represented as a fixed-point integer.
    /// **A special value is used to signify a market order.**
    /// - **Limit Order**: The specific price for the limit.
    /// - **Market Order**: `0` for a SELL, `u64::MAX` for a BUY. This convention
    ///   instructs the matching engine to trade at any available price.
    pub price: u64,

    /// The quantity of the base asset that is remaining to be filled/cancelled
    pub size: u64,

    /// The side of the order book for a new order.
    pub side: Side,

    /// The time-in-force policy for a new order.
    pub time_in_force: TimeInForce,

    /// Timestamp: Time at which the order hits the VexCore
    /// Recorded using Instant::now() for monotonically increasing time
    pub timestamp: u64,

    /// Status of the order
    pub status: Status,

    /// Passive order linked list
    pub events: Option<MatcherTradeEventChain>,

    /// Final balance of the user/maker after this trade
    /// For Deposit/Withdraw commands, only balance[0] is used to represent the asset balance change
    /// For OrderBook commands, balance[0] is base currency, balance[1] is quote currency
    pub balance: [UserBalance; 2], // [0] = base currency, [1] = quote currency

    /// L2 Market Data Snapshot after the order is processed, it is not recorded when the status is Rejected
    pub l2_data: Option<L2MarketData>,
    /// Internal-only routing field: gateway that sent THIS command (not serialized)
    pub route_gateway_id: u8,
    /// Original order size before any fills (set from book order during cancel)
    pub original_size: u64,
}

impl Default for OrderCommand {
    fn default() -> Self {
        Self {
            order_id: 0,
            market_id: 0,
            user_id: 0,
            price: 0,
            size: 0,
            side: Side::Ask,
            client_order_id: 0,
            timestamp: 0,
            time_in_force: TimeInForce::Gtc,
            status: Status::Processing,
            command: OrderCommandType::PlaceOrder,
            events: None,
            balance: [UserBalance::default(); 2],
            l2_data: None,
            route_gateway_id: 0,
            original_size: 0,
        }
    }
}
impl OrderCommand {
    pub fn place_order(
        time_in_force: TimeInForce,
        user_id: u64,
        price: u64,
        size: u64,
        side: Side,
        market_id: u32,
        client_order_id: u64,
    ) -> Self {
        Self {
            command: OrderCommandType::PlaceOrder,
            order_id: 0,
            market_id,
            user_id,
            price,
            size,
            side,
            time_in_force,
            timestamp: 0,
            status: Status::Processing,
            client_order_id,
            events: None,
            balance: [UserBalance::default(); 2],
            l2_data: None,
            route_gateway_id: 0,
            original_size: 0,
        }
    }

    pub fn cancel_order(order_id: u64, user_id: u64, side: Side, market_id: u32) -> Self {
        Self {
            command: OrderCommandType::CancelOrder,
            order_id,
            market_id,
            user_id,
            price: 0,
            size: 0,
            side,
            time_in_force: TimeInForce::Gtc,
            timestamp: 0,
            status: Status::Processing,
            balance: [UserBalance::default(); 2],
            client_order_id: 0,
            events: None,
            l2_data: None,
            route_gateway_id: 0,
            original_size: 0,
        }
    }

    pub fn deposit_funds(user_id: u64, amount: u64, asset: u16) -> Self {
        Self {
            command: OrderCommandType::DepositFunds,
            order_id: 0,
            market_id: asset as u32,
            user_id,
            price: 0,
            size: amount,
            side: Side::Ask,
            time_in_force: TimeInForce::Gtc,
            timestamp: 0,
            status: Status::Processing,
            balance: [UserBalance::default(); 2],
            client_order_id: 0,
            events: None,
            l2_data: None,
            route_gateway_id: 0,
            original_size: 0,
        }
    }

    pub fn withdraw_funds(user_id: u64, amount: u64, asset: u16) -> Self {
        Self {
            command: OrderCommandType::WithdrawFunds,
            order_id: 0,
            market_id: asset as u32,
            user_id,
            price: 0,
            size: amount,
            side: Side::Ask,
            time_in_force: TimeInForce::Gtc,
            timestamp: 0,
            status: Status::Processing,
            balance: [UserBalance::default(); 2],
            client_order_id: 0,
            events: None,
            l2_data: None,
            route_gateway_id: 0,
            original_size: 0,
        }
    }

    pub fn status(&self) -> Status {
        self.status
    }

    pub fn order_id(&self) -> u64 {
        self.order_id
    }

    pub fn user_id(&self) -> u64 {
        self.user_id
    }

    pub fn market_id(&self) -> u32 {
        self.market_id
    }

    pub fn price(&self) -> u64 {
        self.price
    }

    pub fn size(&self) -> u64 {
        self.size
    }

    pub fn timestamp(&self) -> u64 {
        self.timestamp
    }

    pub fn side(&self) -> Side {
        self.side
    }

    pub fn events(&self) -> Option<&MatcherTradeEvent> {
        self.events.as_deref()
    }

    pub fn events_mut(&mut self) -> Option<&mut MatcherTradeEvent> {
        self.events.as_deref_mut()
    }

    pub fn set_size(&mut self, size: u64) {
        self.size = size;
    }

    pub fn set_price(&mut self, price: u64) {
        self.price = price;
    }

    pub fn set_user_id(&mut self, user_id: u64) {
        self.user_id = user_id;
    }

    pub fn set_side(&mut self, side: Side) {
        self.side = side;
    }

    pub fn attach_event(&mut self, event: Box<MatcherTradeEvent>) {
        if let Some(events) = self.events.as_mut() {
            events.push(event);
        } else {
            self.events = Some(MatcherTradeEventChain::new(event));
        }
    }

    pub fn set_status(&mut self, status: Status) {
        self.status = status;
    }
}

/// Status Of The Order Command.
#[derive(
    Debug, PartialEq, Eq, Clone, Copy, Serialize, Deserialize, BorshSerialize, BorshDeserialize,
)]
#[repr(u8)]
pub enum Status {
    /// Rejected { due to Insufficient funds etc}
    Rejected,
    /// Order Placed, but not filled
    Placed,
    /// Cancelled {Direct Cancell order, or IOC, or FOK}
    Cancelled,
    /// Partially Filled Order {Partially filled in case of GTC, IOC}
    PartiallyFilled,
    /// Fully Filled Order {Filled in case of GTC, IOC, FOK}
    Filled,
    /// Processing state
    Processing,
    /// For Deposit/Withdraw commands
    Processed,
}

impl TryFrom<SbeStatus> for Status {
    type Error = SerdeError;

    fn try_from(value: SbeStatus) -> Result<Self, Self::Error> {
        match value {
            SbeStatus::Rejected => Ok(Status::Rejected),
            SbeStatus::Placed => Ok(Status::Placed),
            SbeStatus::Cancelled => Ok(Status::Cancelled),
            SbeStatus::PartiallyFilled => Ok(Status::PartiallyFilled),
            SbeStatus::Filled => Ok(Status::Filled),
            SbeStatus::Processing => Ok(Status::Processing),
            SbeStatus::Processed => Ok(Status::Processed),
            SbeStatus::NullVal => Err(SerdeError::custom("Invalid status: NullVal")),
        }
    }
}

impl From<Status> for SbeStatus {
    fn from(val: Status) -> Self {
        match val {
            Status::Rejected => SbeStatus::Rejected,
            Status::Placed => SbeStatus::Placed,
            Status::Cancelled => SbeStatus::Cancelled,
            Status::PartiallyFilled => SbeStatus::PartiallyFilled,
            Status::Filled => SbeStatus::Filled,
            Status::Processing => SbeStatus::Processing,
            Status::Processed => SbeStatus::Processed,
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct MatcherTradeEvent {
    pub active_order_completed: bool,
    pub matched_order_id: u64,
    pub maker_user_id: u64,
    pub matched_order_completed: bool,
    pub price: u64,
    pub size: u64,
    pub next_event: Option<Box<MatcherTradeEvent>>,
    pub maker_balance: [UserBalance; 2],
    pub maker_remaining_size: u64,
    pub maker_original_size: u64,
}

impl Drop for MatcherTradeEvent {
    fn drop(&mut self) {
        let mut next = self.next_event.take();
        while let Some(mut event) = next {
            next = event.next_event.take();
        }
    }
}

impl PartialEq for MatcherTradeEventChain {
    fn eq(&self, other: &Self) -> bool {
        // Compare the linked events, not the cached tail pointer (PR #177's `tail` is a
        // derived cache and is deliberately not part of the value's identity).
        let mut left = Some(self.head.as_ref());
        let mut right = Some(other.head.as_ref());
        loop {
            match (left, right) {
                (None, None) => return true,
                (Some(l), Some(r)) => {
                    if l != r {
                        return false;
                    }
                    left = l.next_event.as_deref();
                    right = r.next_event.as_deref();
                }
                _ => return false,
            }
        }
    }
}

impl Eq for MatcherTradeEventChain {}

pub struct MatcherTradeEventChain {
    head: Box<MatcherTradeEvent>,
    tail: usize,
}

impl MatcherTradeEventChain {
    fn new(mut event: Box<MatcherTradeEvent>) -> Self {
        let tail = Self::find_tail(&mut event);
        let tail = (tail as *mut MatcherTradeEvent) as usize;
        Self { head: event, tail }
    }

    fn push(&mut self, mut event: Box<MatcherTradeEvent>) {
        if self.tail == 0 {
            let tail = Self::find_tail(&mut self.head);
            self.tail = (tail as *mut MatcherTradeEvent) as usize;
        }
        let next_tail = Self::find_tail(&mut event);
        let next_tail = (next_tail as *mut MatcherTradeEvent) as usize;

        // SAFETY: `tail` points into the linked list owned by `head`. Nodes are heap allocated,
        // so moving the chain does not move them, and mutation requires exclusive access here.
        unsafe {
            (*(self.tail as *mut MatcherTradeEvent)).next_event = Some(event);
        }
        self.tail = next_tail;
    }

    fn find_tail(mut event: &mut MatcherTradeEvent) -> &mut MatcherTradeEvent {
        loop {
            if event.next_event.is_none() {
                return event;
            }
            event = event.next_event.as_deref_mut().unwrap();
        }
    }
}

impl Clone for MatcherTradeEventChain {
    fn clone(&self) -> Self {
        let mut head = self.head.clone();
        let tail = Self::find_tail(&mut head);
        let tail = (tail as *mut MatcherTradeEvent) as usize;
        Self { head, tail }
    }
}

impl fmt::Debug for MatcherTradeEventChain {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.head.fmt(formatter)
    }
}

impl Deref for MatcherTradeEventChain {
    type Target = MatcherTradeEvent;

    fn deref(&self) -> &Self::Target {
        &self.head
    }
}

impl DerefMut for MatcherTradeEventChain {
    fn deref_mut(&mut self) -> &mut Self::Target {
        // The caller can change `next_event`, so force the next append to rebuild the tail.
        self.tail = 0;
        &mut self.head
    }
}

impl MatcherTradeEvent {
    pub fn calc_filled_size(&self) -> u64 {
        let mut size = 0;
        let mut current = Some(self);
        while let Some(event) = current {
            size += event.size;
            current = event.next_event.as_deref();
        }
        size
    }
}

pub fn encode_order_command(order_command: &OrderCommand, buf: &mut [u8]) -> SbeResult<()> {
    let write_buf = WriteBuf::new(buf);
    let mut encoder = OrderCommandMessageEncoder::default();
    encoder = encoder.wrap(write_buf, message_header_codec::ENCODED_LENGTH);
    encoder = encoder.header(0).parent()?;
    encoder.command(order_command.command.into());
    encoder.client_order_id(order_command.client_order_id);
    encoder.order_id(order_command.order_id);
    encoder.market_id(order_command.market_id);
    encoder.user_id(order_command.user_id);
    encoder.price(order_command.price);
    encoder.size(order_command.size);
    encoder.side(order_command.side.into());
    encoder.time_in_force(order_command.time_in_force.into());
    encoder.timestamp(order_command.timestamp);
    encoder.status(order_command.status.into());
    Ok(())
}

pub fn decode_order_command(buf: &[u8]) -> Result<OrderCommand, SerdeError> {
    if buf.len() < ORDERCOMMANDSIZE {
        return Err(SerdeError::custom(format!(
            "OrderCommand buffer is too short: expected at least {ORDERCOMMANDSIZE} bytes, got {}",
            buf.len()
        )));
    }

    let buf = ReadBuf::new(buf);
    let mut decoder = OrderCommandMessageDecoder::default();
    let header = MessageHeaderDecoder::default().wrap(buf, 0);
    if header.block_length() != SBE_BLOCK_LENGTH
        || header.template_id() != SBE_TEMPLATE_ID
        || header.schema_id() != SBE_SCHEMA_ID
    {
        return Err(SerdeError::custom(format!(
            "Invalid OrderCommand SBE header: expected block length {SBE_BLOCK_LENGTH}, template id {SBE_TEMPLATE_ID}, schema id {SBE_SCHEMA_ID}; got block length {}, template id {}, schema id {}",
            header.block_length(),
            header.template_id(),
            header.schema_id()
        )));
    }
    decoder = decoder.header(header, 0);
    Ok(OrderCommand {
        command: decoder.command().try_into()?,
        order_id: decoder.order_id(),
        client_order_id: decoder.client_order_id(),
        market_id: decoder.market_id(),
        user_id: decoder.user_id(),
        price: decoder.price(),
        size: decoder.size(),
        side: decoder.side().try_into()?,
        time_in_force: decoder.time_in_force().try_into()?,
        timestamp: decoder.timestamp(),
        status: decoder.status().try_into()?,
        events: None,
        balance: [UserBalance::default(); 2],
        l2_data: None,
        route_gateway_id: 0,
        original_size: 0,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn deep_matcher_trade_event_chain_drops_iteratively() {
        let mut chain = None;
        for _ in 0..100_000 {
            let mut event = MatcherTradeEvent::default();
            event.next_event = chain;
            chain = Some(Box::new(event));
        }

        drop(chain);
    }

    fn encoded_command() -> [u8; ORDERCOMMANDSIZE] {
        let command = OrderCommand {
            command: OrderCommandType::CancelOrder,
            client_order_id: 11,
            order_id: 22,
            user_id: 33,
            market_id: 44,
            price: 55,
            size: 66,
            side: Side::Bid,
            time_in_force: TimeInForce::Fok,
            timestamp: 77,
            status: Status::Cancelled,
            ..OrderCommand::default()
        };
        let mut buf = [0; ORDERCOMMANDSIZE];
        encode_order_command(&command, &mut buf).unwrap();
        buf
    }

    #[test]
    fn rejects_every_short_buffer_without_panicking() {
        for len in 0..ORDERCOMMANDSIZE {
            assert!(
                decode_order_command(&vec![0; len]).is_err(),
                "buffer length {len} should be rejected"
            );
        }
    }

    #[test]
    fn valid_message_round_trips() {
        let decoded = decode_order_command(&encoded_command()).unwrap();

        assert_eq!(decoded.command, OrderCommandType::CancelOrder);
        assert_eq!(decoded.client_order_id, 11);
        assert_eq!(decoded.order_id, 22);
        assert_eq!(decoded.user_id, 33);
        assert_eq!(decoded.market_id, 44);
        assert_eq!(decoded.price, 55);
        assert_eq!(decoded.size, 66);
        assert_eq!(decoded.side, Side::Bid);
        assert_eq!(decoded.time_in_force, TimeInForce::Fok);
        assert_eq!(decoded.timestamp, 77);
        assert_eq!(decoded.status, Status::Cancelled);
    }

    #[test]
    fn rejects_invalid_sbe_header() {
        for offset in [0, 2, 4] {
            let mut buf = encoded_command();
            buf[offset..offset + 2].copy_from_slice(&0_u16.to_le_bytes());

            assert!(decode_order_command(&buf).is_err());
        }
    }

    use super::{MatcherTradeEvent, OrderCommand};

    fn event_chain(matched_order_ids: &[u64]) -> Box<MatcherTradeEvent> {
        let mut next_event = None;
        for &matched_order_id in matched_order_ids.iter().rev() {
            next_event = Some(Box::new({
                // MatcherTradeEvent implements Drop (PR #179): no functional update.
                let mut e = MatcherTradeEvent::default();
                e.matched_order_id = matched_order_id;
                e.next_event = next_event;
                e
            }));
        }
        next_event.unwrap()
    }

    fn matched_order_ids(command: &OrderCommand) -> Vec<u64> {
        let mut matched_order_ids = Vec::new();
        let mut current = command.events();
        while let Some(event) = current {
            matched_order_ids.push(event.matched_order_id);
            current = event.next_event.as_deref();
        }
        matched_order_ids
    }

    #[test]
    fn attach_event_preserves_order_for_many_fills() {
        let mut command = OrderCommand::default();

        for matched_order_id in 1..=500 {
            command.attach_event(Box::new({
                // MatcherTradeEvent implements Drop (PR #179): no functional update.
                let mut e = MatcherTradeEvent::default();
                e.matched_order_id = matched_order_id;
                e.size = matched_order_id;
                e
            }));
        }

        let mut current = command.events();
        let mut expected_order_id = 1;
        while let Some(event) = current {
            assert_eq!(event.matched_order_id, expected_order_id);
            assert_eq!(event.size, expected_order_id);
            expected_order_id += 1;
            current = event.next_event.as_deref();
        }

        assert_eq!(expected_order_id, 501);

        let mut cloned = command.clone();
        cloned.attach_event(Box::new({
            // MatcherTradeEvent implements Drop (PR #179): no functional update.
            let mut e = MatcherTradeEvent::default();
            e.matched_order_id = 501;
            e.size = 501;
            e
        }));
        assert_eq!(cloned.events().unwrap().calc_filled_size(), 125_751);
        assert_eq!(command.events().unwrap().calc_filled_size(), 125_250);
    }

    #[test]
    fn attach_event_rebuilds_tail_after_mutating_the_chain() {
        let mut command = OrderCommand::default();
        for matched_order_id in 1..=3 {
            command.attach_event(Box::new({
                // MatcherTradeEvent implements Drop (PR #179): no functional update.
                let mut e = MatcherTradeEvent::default();
                e.matched_order_id = matched_order_id;
                e
            }));
        }

        command.events_mut().unwrap().next_event = None;
        command.attach_event(Box::new({
            // MatcherTradeEvent implements Drop (PR #179): no functional update.
            let mut e = MatcherTradeEvent::default();
            e.matched_order_id = 4;
            e
        }));

        let head = command.events().unwrap();
        assert_eq!(head.matched_order_id, 1);
        assert_eq!(head.next_event.as_deref().unwrap().matched_order_id, 4);
        assert!(head.next_event.as_deref().unwrap().next_event.is_none());
    }

    #[test]
    fn attach_event_preserves_prelinked_nodes_and_length() {
        let mut command = OrderCommand::default();
        command.attach_event(event_chain(&[1]));
        command.attach_event(event_chain(&[2, 3]));
        command.attach_event(event_chain(&[4]));

        let matched_order_ids = matched_order_ids(&command);
        assert_eq!(matched_order_ids, [1, 2, 3, 4]);
        assert_eq!(matched_order_ids.len(), 4);
    }

    #[test]
    fn attach_event_preserves_order_across_prelinked_chains() {
        let mut command = OrderCommand::default();
        command.attach_event(event_chain(&[1, 2]));
        command.attach_event(event_chain(&[3, 4, 5]));
        command.attach_event(event_chain(&[6, 7]));

        let matched_order_ids = matched_order_ids(&command);
        assert_eq!(matched_order_ids, [1, 2, 3, 4, 5, 6, 7]);
        assert_eq!(matched_order_ids.len(), 7);
    }

    #[test]
    fn attach_event_recomputes_actual_tail_after_mutable_access() {
        let mut command = OrderCommand::default();
        command.attach_event(event_chain(&[1, 2]));

        let _ = command.events_mut();
        command.attach_event(event_chain(&[3, 4]));
        command.attach_event(event_chain(&[5]));

        assert_eq!(matched_order_ids(&command), [1, 2, 3, 4, 5]);
    }

    fn assert_round_trip(expected: OrderCommand) {
        let mut buffer = [0; ORDERCOMMANDSIZE];
        encode_order_command(&expected, &mut buffer).expect("encoding must succeed");
        let decoded = decode_order_command(&buffer).expect("decoding must succeed");
        assert_eq!(decoded, expected);
    }

    #[test]
    fn order_command_wire_codec_round_trips_every_field_and_boundaries() {
        assert_round_trip(OrderCommand {
            command: OrderCommandType::PlaceOrder,
            client_order_id: 0,
            order_id: 0,
            user_id: 0,
            market_id: 0,
            price: 0,
            size: 0,
            side: Side::Ask,
            time_in_force: TimeInForce::Gtc,
            timestamp: 0,
            status: Status::Rejected,
            ..OrderCommand::default()
        });
        assert_round_trip(OrderCommand {
            command: OrderCommandType::WithdrawFunds,
            client_order_id: u64::MAX,
            order_id: u64::MAX,
            user_id: u64::MAX,
            market_id: u32::MAX,
            price: u64::MAX,
            size: u64::MAX,
            side: Side::Bid,
            time_in_force: TimeInForce::Fok,
            timestamp: u64::MAX,
            status: Status::Processed,
            ..OrderCommand::default()
        });

        for command in [
            OrderCommandType::PlaceOrder,
            OrderCommandType::CancelOrder,
            OrderCommandType::DepositFunds,
            OrderCommandType::WithdrawFunds,
        ] {
            assert_round_trip(OrderCommand {
                command,
                ..OrderCommand::default()
            });
        }
        for side in [Side::Ask, Side::Bid] {
            assert_round_trip(OrderCommand {
                side,
                ..OrderCommand::default()
            });
        }
        for time_in_force in [TimeInForce::Gtc, TimeInForce::Ioc, TimeInForce::Fok] {
            assert_round_trip(OrderCommand {
                time_in_force,
                ..OrderCommand::default()
            });
        }
        for status in [
            Status::Rejected,
            Status::Placed,
            Status::Cancelled,
            Status::PartiallyFilled,
            Status::Filled,
            Status::Processing,
            Status::Processed,
        ] {
            assert_round_trip(OrderCommand {
                status,
                ..OrderCommand::default()
            });
        }
    }
}
