use crate::{L2MarketData, OrderCommandType, Side, TimeInForce, UserBalance};
use borsh::{BorshDeserialize, BorshSerialize};
use sbe_order::message_header_codec::{self, MessageHeaderDecoder};
use sbe_order::order_command_message_codec::{
    OrderCommandMessageDecoder, OrderCommandMessageEncoder,
};
use sbe_order::status::Status as SbeStatus;
use sbe_order::{ReadBuf, SbeResult, WriteBuf};
use serde::de::Error;
use serde::de::value::Error as SerdeError;
use serde::{Deserialize, Serialize};

// Size of the serialized OrderCommand in bytes
// Header: 8 bytes
// command: 1 byte
// order_id: 8 bytes
// timestamp: 8 bytes
// user_id: 8 bytes
// market_id: 4 bytes
// price: 8 bytes
// size: 8 bytes
// side: 1 byte
// time_in_force: 1 byte
pub const ORDERCOMMANDSIZE: usize = 64;

/// This is the size of each frame sent or received via Aeron.
/// It is a nearest multiple of 32 bytes that can hold an OrderCommand.
pub const FRAMESIZE: i64 = 96;

/// OrderCommand: OrderCommand Plays the central role throughout the processing of the Order.
/// It is created in the Gateway, and processed in VexCore in different processors through the Disruptor
#[derive(Debug, Clone)]
#[repr(C)]
pub struct OrderCommand {
    // --- Universal Fields (Relevant for all command types) ---
    /// The type of command this struct represents. Consumers **must** check this
    /// field first to determine how to process the rest of the data.
    pub command: OrderCommandType,

    /// Client Order ID
    pub client_order_id: u64,

    /// The primary identifier for the order. Its meaning depends on `command`.
    /// - For `PlaceOrder`: This is the **new**, unique ID generated by the gateway.
    /// - For `CancelOrder`: This is the ID of the **existing** order to be canceled.
    pub order_id: u64,

    /// The unique identifier of the user initiating the command.
    /// For 'PlaceOrder' : This is the actual user id
    /// For 'CancelOrder': this is set to the gateway id inside the OrderCommand Field
    /// This is required because, in the existing scenarior the gateway id(required to send
    /// back the response to gateway with gateway_id in the events handler) not present in
    /// the OrderCommand Field, so it is encoded in the order_id by the snowflake algorithm
    /// Everything works correctly untill the order_id is itself wrong that is sent the gateway
    /// and user_id is not essential for the CancelOrder hence it is the best choice to place
    /// gateway id to send response correctly.
    pub user_id: u64,

    /// The identifier for the market this command targets.
    pub market_id: u32,

    // --- `PlaceOrder`-Specific Fields ---
    // These fields are only valid if `command` is `PlaceOrder`. They are
    // undefined for `CancelOrder` and should be ignored by the processor.
    /// The price for the new order, represented as a fixed-point integer.
    /// **A special value is used to signify a market order.**
    /// - **Limit Order**: The specific price for the limit.
    /// - **Market Order**: `0` for a SELL, `u64::MAX` for a BUY. This convention
    ///   instructs the matching engine to trade at any available price.
    pub price: u64,

    /// The quantity of the base asset that is remaining to be filled/cancelled
    pub size: u64,

    /// The side of the order book for a new order.
    pub side: Side,

    /// The time-in-force policy for a new order.
    pub time_in_force: TimeInForce,

    /// Timestamp: Time at which the order hits the VexCore
    /// Recorded using Instant::now() for monotonically increasing time
    pub timestamp: u64,

    /// Status of the order
    pub status: Status,

    /// Passive order linked list
    pub events: Option<Box<MatcherTradeEvent>>,

    /// Final balance of the user/maker after this trade
    /// For Deposit/Withdraw commands, only balance[0] is used to represent the asset balance change
    /// For OrderBook commands, balance[0] is base currency, balance[1] is quote currency
    pub balance: [UserBalance; 2], // [0] = base currency, [1] = quote currency

    /// L2 Market Data Snapshot after the order is processed, it is not recorded when the status is Rejected
    pub l2_data: Option<L2MarketData>,
    /// Internal-only routing field: gateway that sent THIS command (not serialized)
    pub route_gateway_id: u8,
}

impl Default for OrderCommand {
    fn default() -> Self {
        Self {
            order_id: 0,
            market_id: 0,
            user_id: 0,
            price: 0,
            size: 0,
            side: Side::Ask,
            client_order_id: 0,
            timestamp: 0,
            time_in_force: TimeInForce::Gtc,
            status: Status::Processing,
            command: OrderCommandType::PlaceOrder,
            events: None,
            balance: [UserBalance::default(); 2],
            l2_data: None,
            route_gateway_id: 0,
        }
    }
}
impl OrderCommand {
    pub fn place_order(
        time_in_force: TimeInForce,
        user_id: u64,
        price: u64,
        size: u64,
        side: Side,
        market_id: u32,
        client_order_id: u64,
    ) -> Self {
        Self {
            command: OrderCommandType::PlaceOrder,
            order_id: 0,
            market_id,
            user_id,
            price,
            size,
            side,
            time_in_force,
            timestamp: 0,
            status: Status::Processing,
            client_order_id,
            events: None,
            balance: [UserBalance::default(); 2],
            l2_data: None,
            route_gateway_id: 0,
        }
    }

    pub fn cancel_order(order_id: u64, side: Side, market_id: u32) -> Self {
        Self {
            command: OrderCommandType::CancelOrder,
            order_id,
            market_id,
            user_id: 0,
            price: 0,
            size: 0,
            side,
            time_in_force: TimeInForce::Gtc,
            timestamp: 0,
            status: Status::Processing,
            balance: [UserBalance::default(); 2],
            client_order_id: 0,
            events: None,
            l2_data: None,
            route_gateway_id: 0,
        }
    }

    pub fn deposit_funds(user_id: u64, amount: u64, asset: u16) -> Self {
        Self {
            command: OrderCommandType::DepositFunds,
            order_id: 0,
            market_id: asset as u32,
            user_id,
            price: 0,
            size: amount,
            side: Side::Ask,
            time_in_force: TimeInForce::Gtc,
            timestamp: 0,
            status: Status::Processing,
            balance: [UserBalance::default(); 2],
            client_order_id: 0,
            events: None,
            l2_data: None,
            route_gateway_id: 0,
        }
    }

    pub fn withdraw_funds(user_id: u64, amount: u64, asset: u16) -> Self {
        Self {
            command: OrderCommandType::WithdrawFunds,
            order_id: 0,
            market_id: asset as u32,
            user_id,
            price: 0,
            size: amount,
            side: Side::Ask,
            time_in_force: TimeInForce::Gtc,
            timestamp: 0,
            status: Status::Processing,
            balance: [UserBalance::default(); 2],
            client_order_id: 0,
            events: None,
            l2_data: None,
            route_gateway_id: 0,
        }
    }

    pub fn status(&self) -> Status {
        self.status
    }

    pub fn order_id(&self) -> u64 {
        self.order_id
    }

    pub fn user_id(&self) -> u64 {
        self.user_id
    }

    pub fn market_id(&self) -> u32 {
        self.market_id
    }

    pub fn price(&self) -> u64 {
        self.price
    }

    pub fn size(&self) -> u64 {
        self.size
    }

    pub fn timestamp(&self) -> u64 {
        self.timestamp
    }

    pub fn side(&self) -> Side {
        self.side
    }

    pub fn events(&self) -> Option<&MatcherTradeEvent> {
        self.events.as_deref()
    }

    pub fn events_mut(&mut self) -> Option<&mut MatcherTradeEvent> {
        self.events.as_mut().map(|e| e.as_mut())
    }

    pub fn set_size(&mut self, size: u64) {
        self.size = size;
    }

    pub fn set_price(&mut self, price: u64) {
        self.price = price;
    }

    pub fn set_user_id(&mut self, user_id: u64) {
        self.user_id = user_id;
    }

    pub fn attatch_event(&mut self, event: Box<MatcherTradeEvent>) {
        if let Some(mut tail) = self.events.as_mut() {
            while tail.next_event.is_some() {
                tail = tail.next_event.as_mut().unwrap();
            }
            tail.next_event = Some(event);
        } else {
            self.events = Some(event);
        }
    }

    pub fn set_status(&mut self, status: Status) {
        self.status = status;
    }
}

/// Status Of The Order Command.
#[derive(
    Debug, PartialEq, Eq, Clone, Copy, Serialize, Deserialize, BorshSerialize, BorshDeserialize,
)]
#[repr(u8)]
pub enum Status {
    /// Rejected { due to Insufficient funds etc}
    Rejected,
    /// Order Placed, but not filled
    Placed,
    /// Cancelled {Direct Cancell order, or IOC, or FOK}
    Cancelled,
    /// Partially Filled Order {Partially filled in case of GTC, IOC}
    PartiallyFilled,
    /// Fully Filled Order {Filled in case of GTC, IOC, FOK}
    Filled,
    /// Processing state
    Processing,
    /// For Deposit/Withdraw commands
    Processed,
}

impl TryFrom<SbeStatus> for Status {
    type Error = SerdeError;

    fn try_from(value: SbeStatus) -> Result<Self, Self::Error> {
        match value {
            SbeStatus::Rejected => Ok(Status::Rejected),
            SbeStatus::Placed => Ok(Status::Placed),
            SbeStatus::Cancelled => Ok(Status::Cancelled),
            SbeStatus::PartiallyFilled => Ok(Status::PartiallyFilled),
            SbeStatus::Filled => Ok(Status::Filled),
            SbeStatus::Processing => Ok(Status::Processing),
            SbeStatus::Processed => Ok(Status::Processed),
            SbeStatus::NullVal => Err(SerdeError::custom("Invalid status: NullVal")),
        }
    }
}

impl Into<SbeStatus> for Status {
    fn into(self) -> SbeStatus {
        match self {
            Status::Rejected => SbeStatus::Rejected,
            Status::Placed => SbeStatus::Placed,
            Status::Cancelled => SbeStatus::Cancelled,
            Status::PartiallyFilled => SbeStatus::PartiallyFilled,
            Status::Filled => SbeStatus::Filled,
            Status::Processing => SbeStatus::Processing,
            Status::Processed => SbeStatus::Processed,
        }
    }
}

#[derive(Debug, Clone, Default)]
pub struct MatcherTradeEvent {
    pub active_order_completed: bool,
    pub matched_order_id: u64,
    pub maker_user_id: u64,
    pub matched_order_completed: bool,
    pub price: u64,
    pub size: u64,
    pub next_event: Option<Box<MatcherTradeEvent>>,
    pub maker_balance: [UserBalance; 2], // [0] = base currency, [1] = quote currency
}

impl MatcherTradeEvent {
    pub fn calc_filled_size(&self) -> u64 {
        let mut size = 0;
        let mut current = Some(self);
        while let Some(event) = current {
            size += event.size;
            current = event.next_event.as_deref();
        }
        size
    }
}

pub fn encode_order_command(order_command: &OrderCommand, buf: &mut [u8]) -> SbeResult<()> {
    let write_buf = WriteBuf::new(buf);
    let mut encoder = OrderCommandMessageEncoder::default();
    encoder = encoder.wrap(write_buf, message_header_codec::ENCODED_LENGTH);
    encoder = encoder.header(0).parent()?;
    encoder.command(order_command.command.into());
    encoder.client_order_id(order_command.client_order_id);
    encoder.order_id(order_command.order_id);
    encoder.market_id(order_command.market_id);
    encoder.user_id(order_command.user_id);
    encoder.price(order_command.price);
    encoder.size(order_command.size);
    encoder.side(order_command.side.into());
    encoder.time_in_force(order_command.time_in_force.into());
    encoder.timestamp(order_command.timestamp);
    encoder.status(order_command.status.into());
    Ok(())
}

pub fn decode_order_command(buf: &[u8]) -> Result<OrderCommand, SerdeError> {
    let buf = ReadBuf::new(buf);
    let mut decoder = OrderCommandMessageDecoder::default();
    let header = MessageHeaderDecoder::default().wrap(buf, 0);
    decoder = decoder.header(header, 0);
    Ok(OrderCommand {
        command: decoder.command().try_into()?,
        order_id: decoder.order_id(),
        client_order_id: decoder.client_order_id(),
        market_id: decoder.market_id(),
        user_id: decoder.user_id(),
        price: decoder.price(),
        size: decoder.size(),
        side: decoder.side().try_into()?,
        time_in_force: decoder.time_in_force().try_into()?,
        timestamp: decoder.timestamp(),
        status: decoder.status().try_into()?, // Default status since decoder doesn't have status method
        events: None,
        balance: [UserBalance::default(); 2],
        l2_data: None,
        route_gateway_id: 0,
    })
}
