use crate::{OrderCommandType, Side, TimeInForce};
use sbe_order::message_header_codec::{self, MessageHeaderDecoder};
use sbe_order::order_command_message_codec::{
    OrderCommandMessageDecoder, OrderCommandMessageEncoder,
};
use sbe_order::{ReadBuf, SbeResult, WriteBuf};
use serde::de::value::Error as SerdeError;

/// OrderCommand: OrderCommand Plays the central role throughout the processing of the Order.
/// It is created in the Gateway, and processed in VexCore in different processors through the Disruptor
#[derive(Debug, Clone)]
#[repr(C)]
pub struct OrderCommand {
    // --- Universal Fields (Relevant for all command types) ---
    /// The type of command this struct represents. Consumers **must** check this
    /// field first to determine how to process the rest of the data.
    pub command: OrderCommandType,

    /// The primary identifier for the order. Its meaning depends on `command`.
    /// - For `PlaceOrder`: This is the **new**, unique ID generated by the gateway.
    /// - For `CancelOrder`: This is the ID of the **existing** order to be canceled.
    pub order_id: u64,

    /// Timestamp: Time at which the order hits the VexCore
    /// Recorded using Instant::now() for monotonically increasing time
    pub timestamp: u64,

    /// The unique identifier of the user initiating the command.
    /// Used for routing, risk checks, and authorization.
    pub user_id: u64,

    /// The identifier for the market this command targets.
    pub market_id: u32,

    // --- `PlaceOrder`-Specific Fields ---
    // These fields are only valid if `command` is `PlaceOrder`. They are
    // undefined for `CancelOrder` and should be ignored by the processor.
    /// The price for the new order, represented as a fixed-point integer.
    /// **A special value is used to signify a market order.**
    /// - **Limit Order**: The specific price for the limit.
    /// - **Market Order**: `0` for a SELL, `u64::MAX` for a BUY. This convention
    ///   instructs the matching engine to trade at any available price.
    pub price: u64,

    /// The quantity of the asset to be bought or sold for a new order.
    pub size: u64,

    /// The side of the order book for a new order.
    pub side: Side,

    /// The time-in-force policy for a new order.
    pub time_in_force: TimeInForce,
}

impl Default for OrderCommand {
    fn default() -> Self {
        Self {
            order_id: 0,
            market_id: 0,
            user_id: 0,
            price: 0,
            size: 0,
            side: Side::Ask,
            timestamp: 0,
            time_in_force: TimeInForce::Gtc,
            command: OrderCommandType::PlaceOrder,
        }
    }
}
impl OrderCommand {
    pub fn new_order(
        time_in_force: TimeInForce,
        order_id: u64,
        user_id: u64,
        price: u64,
        size: u64,
        side: Side,
    ) -> Self {
        Self {
            command: OrderCommandType::PlaceOrder,
            order_id,
            market_id: 0,
            user_id,
            price,
            size,
            side,
            time_in_force,
            timestamp: 0,
        }
    }

    pub fn cancel(order_id: u64, side: Side, market_id: u32) -> Self {
        Self {
            command: OrderCommandType::CancelOrder,
            order_id,
            market_id,
            user_id: 0,
            price: 0,
            size: 0,
            side,
            time_in_force: TimeInForce::Gtc,
            timestamp: 0,
        }
    }
}

pub struct ProcessedOrderCommand {
    status: Status,
    order_id: u64,
    market_id: u32,
    taker_id: u64,
    price: u64,
    size: u64,
    side: Side,
    timestamp: u64,
    events: Option<Box<MatcherTradeEvent>>,
}

impl ProcessedOrderCommand {
    pub fn new(status: Status, order_id: u64, taker_id: u64 ,market_id: u32, price: u64 , size: u64, timestamp: u64 , taker_side: Side) -> Self {
        Self {
            status,
            order_id,
            market_id,
            taker_id,
            price,
            size,
            side: taker_side,
            timestamp,
            events: None,
        }
    }

    pub fn status(&self) -> Status {
        self.status
    }

    pub fn order_id(&self) -> u64 {
        self.order_id
    }

    pub fn taker_id(&self) -> u64 {
        self.taker_id
    }

    pub fn market_id(&self) -> u32 {
        self.market_id
    }

    pub fn price(&self) -> u64 {
        self.price
    }

    pub fn size(&self) -> u64 {
        self.size
    }

    pub fn timestamp(&self) -> u64 {
        self.timestamp
    }

    pub fn side(&self) -> Side {
        self.side
    }

    pub fn events(&self) -> Option<&MatcherTradeEvent> {
        self.events.as_deref()
    }

    pub fn attatch_event(&mut self, event: Box<MatcherTradeEvent>) {
        if let Some(mut tail) = self.events.as_mut() {
            while tail.next_event.is_some() {
                tail = tail.next_event.as_mut().unwrap();
            }
            tail.next_event = Some(event);
        } else {
            self.events = Some(event);
        }
    }

    pub fn set_status(&mut self, status: Status) {
        self.status = status;
    }
}

/// Status Of The Order Command.
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
#[repr(u8)]
pub enum Status {
    /// Rejected { due to Insufficient funds etc}
    Rejected,
    /// Order Placed, but not filled
    Placed,
    /// Cancelled {Direct Cancell order, or IOC, or FOK}
    Cancelled,
    /// Partially Filled Order {Partially filled in case of GTC, IOC}
    PartiallyFilled,
    /// Fully Filled Order {Filled in case of GTC, IOC, FOK}
    Filled,
}

#[derive(Debug, Clone, Default)]
pub struct MatcherTradeEvent {
    pub active_order_completed: bool,
    pub matched_order_id: u64,
    pub maker_user_id: u64,
    pub matched_order_completed: bool,
    pub price: u64,
    pub size: u64,
    pub next_event: Option<Box<MatcherTradeEvent>>,
}

impl MatcherTradeEvent {
    pub fn calc_filled_size(&self) -> u64 {
        let mut size = 0;
        let mut current = Some(self);
        while let Some(event) = current {
            size += event.size;
            current = event.next_event.as_deref();
        }
        size
    }
}

pub fn encode_order_command(order_command: OrderCommand, buf: &mut [u8]) -> SbeResult<()> {
    let write_buf = WriteBuf::new(buf);
    let mut encoder = OrderCommandMessageEncoder::default();
    encoder = encoder.wrap(write_buf, message_header_codec::ENCODED_LENGTH);
    encoder = encoder.header(0).parent()?;
    encoder.command(order_command.command.into());
    encoder.order_id(order_command.order_id);
    encoder.market_id(order_command.market_id);
    encoder.user_id(order_command.user_id);
    encoder.price(order_command.price);
    encoder.size(order_command.size);
    encoder.side(order_command.side.into());
    encoder.time_in_force(order_command.time_in_force.into());
    encoder.timestamp(order_command.timestamp);
    Ok(())
}

pub fn decode_order_command(buf: &[u8]) -> Result<OrderCommand, SerdeError> {
    let buf = ReadBuf::new(buf);
    let mut decoder = OrderCommandMessageDecoder::default();
    let header = MessageHeaderDecoder::default().wrap(buf, 0);
    decoder = decoder.header(header, 0);
    Ok(OrderCommand {
        command: decoder.command().try_into()?,
        order_id: decoder.order_id(),
        market_id: decoder.market_id(),
        user_id: decoder.user_id(),
        price: decoder.price(),
        size: decoder.size(),
        side: decoder.side().try_into()?,
        time_in_force: decoder.time_in_force().try_into()?,
        timestamp: decoder.timestamp(),
    })
}
